/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	Pass: Build luminance histogram for auto exposure
    Reference:  https://knarkowicz.wordpress.com/2016/01/09/automatic-exposure/
                https://bruop.github.io/exposure/

--------------------------------------------------------------------------------
*/

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(0.5, 0.5);

//======// Uniform //=============================================================================//

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#define SSBO_DECLARED_TPYE restrict
#include "/lib/universal/SSBO.glsl"

//======// Shared Memory //=======================================================================//

shared uint sharedHistogram[HISTOGRAM_BIN_COUNT];

//======// Function //============================================================================//

const float autoEvRange = AUTO_EV_MAX - AUTO_EV_MIN;
const float autoEvRangeInv = 1.0 / autoEvRange;

uint histogramLumToBin(float lum) {
    float bin = log2(lum) * autoEvRangeInv - (AUTO_EV_MIN * autoEvRangeInv);
	return uint(saturate(bin) * float(HISTOGRAM_BIN_COUNT - 1u));
}

//======// Main //================================================================================//
void main() {
	uint index = gl_LocalInvocationIndex;
	ivec2 texelPos = ivec2(gl_GlobalInvocationID.xy);

	// Initialize
	sharedHistogram[index] = 0u;
	barrier();

	if (all(lessThan(texelPos, textureSize(colortex4, 0) >> 1u))) {
		// Compute luminance
		float luminance = luminance(texelFetch(colortex4, texelPos, 0).rgb);

		// Update histogram
		uint binIndex = histogramLumToBin(luminance);
		atomicAdd(sharedHistogram[binIndex], 1u);
	}
	barrier();

	// Store histogram
	if (index < HISTOGRAM_BIN_COUNT) {
    	atomicAdd(exposure.histogram[index], sharedHistogram[index]);
	}
}