/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

restrict writeonly uniform image2D colorimg0; // Motion blur output

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

vec3 MotionBlur(ivec2 texelPos) {
	vec2 motionVector = texelFetch(colortex3, texelPos, 0).xy;
	float motionNorm = inversesqrt(sdot(motionVector));

	if (motionNorm > 1e6) return texelFetch(colortex1, texelPos, 0).rgb;
	motionVector *= saturate(motionNorm);

	const float strength = MOTION_BLUR_STRENGTH / float(MOTION_BLUR_SAMPLES) * 0.01;
	motionVector *= strength / max(frameTime, 1e-3) * scaledViewSize;

	float dither = BlueNoise(texelPos, frameCounter);

	vec2 sampleCoord = vec2(texelPos) + 0.5 + motionVector * dither;
	sampleCoord -= motionVector * MOTION_BLUR_SAMPLES * 0.5;

	vec3 sum = vec3(0.0);
	float sumWeight = 0.0;

	for (uint i = 0u; i < MOTION_BLUR_SAMPLES; ++i, sampleCoord += motionVector) {
		if (clamp(sampleCoord, vec2(0.0), scaledViewSize - 1.0) == sampleCoord) {
			sum += texelFetch(colortex1, ivec2(sampleCoord), 0).rgb;
			++sumWeight;
		}
	}

	if (sumWeight < EPS) return texelFetch(colortex1, texelPos, 0).rgb;

	return sum * rcp(sumWeight);
}

//======// Main //================================================================================//
void main() {
	uvec2 localPos = RemapThread16x16(gl_LocalInvocationIndex);
	ivec2 texelPos = scaleTexelPos(ivec2(localPos + gl_WorkGroupID.xy * gl_WorkGroupSize.xy));

	imageStore(colorimg0, texelPos, vec4(MotionBlur(texelPos), texelFetch(colortex0, texelPos, 0).w));
}
