/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

    Pass: Upscaling the scene color

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout(local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

restrict writeonly uniform image2D colorimg5; // Upscaled scene color

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#define FSR1_EASU_IN colortex0
#define FSR1_EASU_OUT colorimg5
#include "/ffx/fsr1/ffx_fsr1.glsl"

//======// Main //================================================================================//
void main() {
    fsr1Easu(scaledViewSize, scaledViewSize, originViewSize);
}
