/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

#define PASS_SKY_MAP

//======// Input //===============================================================================//

layout(local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(18, 12, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image2D skyEnvMapImg;

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

#include "/lib/atmosphere/Common.glsl"

#include "/lib/atmosphere/clouds/Render.glsl"
#include "/lib/atmosphere/AtmosphericFog.glsl"

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);

	// Checkerboard render
	ivec2 offset = checkerboardOffset2x2[frameCounter & 3];
	if ((tid & 1) == offset || historyReset) {
		vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(skyEnvMapImg));

		vec3 worldDir = UnprojectCubemap(uv, 96.0);
		vec3 skyRadiance = AtmosphereSkyView(atmosphereViewPos, worldDir, sunDirWorld);

		vec2 noise = SampleStbnVec2(tid, frameCounter);

		#ifdef CLOUDS
			vec4 cloudData = RenderClouds(worldDir, noise);
			CompositeClouds(skyRadiance, cloudData, worldDir);
		#endif

		#ifdef VOLUMETRIC_FOG
			if (isEyeInWater == 0) {
				mat2x3 volFogData = RaymarchAtmosphericFog(vec3(0.0), worldDir * FLT_MAX, noise.x, VF_MAX_SAMPLES >> 1);
				skyRadiance = ApplyFog(skyRadiance, volFogData);
			}
		#endif

		// Accumulate
		vec4 history = texelFetch(skyEnvMapTex, tid, 0);
		history.a *= float(!historyReset);

		skyRadiance = mix(history.rgb, skyRadiance, rcp(min(++history.a, 64.0)));
		imageStore(skyEnvMapImg, tid, vec4(skyRadiance, history.a));
	}
}
