/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

#define PASS_GEN_SKY_MAP

//======// Input //===============================================================================//

layout(local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(18, 12, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image2D skyEnvMapImg;

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

#include "/lib/atmosphere/Common.glsl"

#include "/lib/atmosphere/clouds/Render.glsl"
#include "/lib/atmosphere/AtmosphericFog.glsl"

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);

    vec4 history = texelFetch(skyEnvMapTex, tid, 0);

	// Checkerboard render
	ivec2 offset = checkerboardOffset2x2[frameCounter & 3];
	if ((tid & 1) == offset || history.a < 4.0) {
		vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(skyEnvMapImg));

		vec3 worldDir = UnprojectCubemap(uv, 96.0);
		vec3 skyRadiance = AtmosphereSkyView(atmosphereViewPos, worldDir, sunDirWorld);

		vec2 noise = SampleStbnVec2(tid, frameCounter);

        // Clouds
		#ifdef CLOUDS
			CloudRenderResult cloudResult = RenderClouds(worldDir, noise, skyRadiance);
            skyRadiance = skyRadiance * cloudResult.transmittance + cloudResult.scatteredLight;
		#endif

	    // Atmospheric fog
		if (isEyeInWater == 0) {
		    #ifdef VOLUMETRIC_FOG
				mat2x3 volFogData = RaymarchAtmosphericFog(
                    vec3(0.0), worldDir * lodRenderDist, noise.x, VF_MAX_SAMPLES >> 1
                );
				skyRadiance = ApplyFog(skyRadiance, volFogData);
		    #else
				float cameraHeight = eyeAltitude - VF_HEIGHT;

				ExponentialHeightFog(
					global.directIlluminance * eyeSkylightSmooth,
					global.skyUpIlluminance * eyeSkylightSmooth,
					lodRenderDist,
					cameraHeight,
					cameraHeight + worldDir.y * lodRenderDist,
					dot(shadowDirWorld, worldDir),
					skyRadiance
				);
		    #endif
		}

		history.a *= float(!historyReset);

        // Accumulate
		skyRadiance = mix(history.rgb, skyRadiance, rcp(min(++history.a, 32.0)));
		imageStore(skyEnvMapImg, tid, vec4(skyRadiance, history.a));
	}
}
