/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	Pass: Compute and store global SSBO

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 1, local_size_y = 1) in;
const ivec3 workGroups = ivec3(1, 1, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#define SSBO_DECLARED_TPYE restrict
#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"
#include "/lib/atmosphere/clouds/Common.glsl"

//======// Main //================================================================================//
void main() {
	// Compute illuminance
	vec3 sunIlluminance = sunIrradiance * AtmosphereTransmittanceToSun(atmosphereViewPos, sunDirWorld);
	vec3 moonIlluminance = moonIrradiance * AtmosphereTransmittanceToSun(atmosphereViewPos, moonDirWorld);
	global.directIlluminance = sunIlluminance + moonIlluminance;

	// Avoid the misalignment at sunrise and sunset
	global.directIlluminance *= smoothstep(0.0, 0.01, shadowDirWorld.y);

	global.worldTimeDiff = worldTime - global.lastWorldTime;
    global.lastWorldTime = worldTime;

	#ifdef CLOUD_SHADOWS
		mat4 projMat = BuildOrthoMat(CLOUD_SHADOW_DISTANCE * 32.0, CLOUD_SHADOW_DISTANCE * 32.0, 0.0, cumulusTopRadius);
		cloud.shadowViewProj = projMat * shadowModelView;
		cloud.shadowViewProjInv = inverse(cloud.shadowViewProj);
	#endif
}
