#====# Full #======================================================================================#

# block.10001 =

# Water
block.10003 = \
#ifdef IRIS_TAG_SUPPORT
    %minecraft:water \
#endif
water

# Lava
block.10007 = lava

# Leaves
block.10013 = \
oak_leaves spruce_leaves birch_leaves jungle_leaves acacia_leaves dark_oak_leaves azalea_leaves flowering_azalea_leaves cherry_leaves \
#ifdef IRIS_TAG_SUPPORT
    %minecraft:leaves \
#endif
mangrove_leaves

#====# Lights #====================================================================================#

# Total emissive
block.10020 = \
            candle:lit=true white_candle:lit=true orange_candle:lit=true magenta_candle:lit=true light_blue_candle:lit=true yellow_candle:lit=true lime_candle:lit=true pink_candle:lit=true gray_candle:lit=true light_gray_candle:lit=true cyan_candle:lit=true purple_candle:lit=true blue_candle:lit=true brown_candle:lit=true green_candle:lit=true red_candle:lit=true black_candle:lit=true \
            ochre_froglight verdant_froglight pearlescent_froglight \
            redstone_block lapis_block emerald_block

# Torch like
block.10021 = \
torch wall_torch campfire:lit=true lantern \
furnace:lit=true blast_furnace:lit=true smoker:lit=true lava_cauldron

# Fire
block.10022 = fire

# Glowstone like
block.10023 = glowstone jack_o_lantern magma_block shroomlight redstone_lamp:lit=true

# Sea lantern like
block.10024 = sea_lantern end_rod warped_stem warped_hyphae redstone_wire crimson_stem crimson_hyphae

# Redstone
block.10025 = redstone_torch:lit=true redstone_wall_torch:lit=true repeater comparator

# Soul fire
block.10026 = sea_pickle dragon_head spawner \
              enchanting_table \
              soul_campfire:lit=true soul_torch soul_wall_torch soul_lantern soul_fire respawn_anchor crying_obsidian

# Amethyst
block.10027 = \
small_amethyst_bud medium_amethyst_bud large_amethyst_bud amethyst_cluster \
calibrated_sculk_sensor \

# Glowberry
block.10028 = cave_vines_plant:berries=true cave_vines:berries=true

# Rails
block.10029 = powered_rail:powered=true activator_rail:powered=true detector_rail:powered=true observer:powered=true

# Beacon core
block.10030 = beacon

# Sculk
block.10031 = sculk sculk_catalyst sculk_shrieker sculk_vein sculk_sensor

# Glow lichen
block.10032 = glow_lichen

# Partial emissive
block.10033 = weeping_vines weeping_vines_plant chorus_plant chorus_flower crimson_fungus warped_fungus

# Middle emissive
block.10034 = brewing_stand \
              candle_cake:lit=true white_candle_cake:lit=true orange_candle_cake:lit=true magenta_candle_cake:lit=true light_blue_candle_cake:lit=true yellow_candle_cake:lit=true lime_candle_cake:lit=true pink_candle_cake:lit=true gray_candle_cake:lit=true light_gray_candle_cake:lit=true cyan_candle_cake:lit=true purple_candle_cake:lit=true blue_candle_cake:lit=true brown_candle_cake:lit=true green_candle_cake:lit=true red_candle_cake:lit=true black_candle_cake:lit=true


#====# Has SSS #===================================================================================#

# Weak SSS
block.10037 = white_wool orange_wool magenta_wool light_blue_wool yellow_wool lime_wool pink_wool gray_wool light_gray_wool cyan_wool purple_wool blue_wool brown_wool green_wool red_wool black_wool \
              white_carpet orange_carpet magenta_carpet light_blue_carpet yellow_carpet lime_carpet pink_carpet gray_carpet light_gray_carpet cyan_carpet purple_carpet blue_carpet brown_carpet green_carpet red_carpet black_carpet \
              white_wall_banner orange_wall_banner magenta_wall_banner light_blue_wall_banner yellow_wall_banner lime_wall_banner pink_wall_banner gray_wall_banner light_gray_wall_banner cyan_wall_banner purple_wall_banner blue_wall_banner brown_wall_banner green_wall_banner red_wall_banner black_wall_banner white_banner orange_banner magenta_banner light_blue_banner yellow_banner lime_banner pink_banner gray_banner light_gray_banner cyan_banner purple_banner blue_banner brown_banner green_banner red_banner black_banner \
              white_bed orange_bed magenta_bed light_blue_bed yellow_bed lime_bed pink_bed gray_bed light_gray_bed cyan_bed purple_bed blue_bed brown_bed green_bed red_bed black_bed \
              hay_block

# Strong SSS
block.10038 = frosted_ice blue_ice packed_ice snow snow_block powder_snow honeycomb_block brown_mushroom_block red_mushroom_block \
              quartz_block quartz_stairs quartz_slab chiseled_quartz_block quartz_bricks quartz_pillar smooth_quartz smooth_quartz_stairs smooth_quartz_slab amethyst_block budding_amethyst

# End portal and gateway
block.10046 = end_portal end_gateway

#====# Plants #====================================================================================#

# Short plants
block.11000 = \
#ifdef IRIS_TAG_SUPPORT
%crops %small_flowers \
#endif
fern grass \
short_grass \
nether_sprouts warped_roots crimson_roots \
wheat carrots potatoes beetroots seagrass \
dandelion poppy blue_orchid allium azure_bluet red_tulip orange_tulip white_tulip pink_tulip oxeye_daisy cornflower sweet_berry_bush lily_of_the_valley wither_rose torchflower

# Tall plants - upper half
block.11001 = \
tall_grass:half=upper large_fern:half=upper sunflower:half=upper lilac:half=upper rose_bush:half=upper peony:half=upper tall_seagrass:half=upper pitcher_plant:half=upper

# Tall plants - lower half
block.11002 = \
tall_grass:half=lower large_fern:half=lower sunflower:half=lower lilac:half=lower rose_bush:half=lower peony:half=lower tall_seagrass:half=lower pitcher_plant:half=lower

# Unwaveable
block.11003 = \
#ifdef IRIS_TAG_SUPPORT
%saplings \
#endif
oak_sapling spruce_sapling birch_sapling jungle_sapling acacia_sapling dark_oak_sapling mangrove_propagule dead_bush \
kelp kelp_plant \
azalea flowering_azalea \
bamboo bamboo_sapling sugar_cane mangrove_roots cactus \
pumpkin_stem attached_pumpkin_stem melon_stem attached_melon_stem \
spore_blossom small_dripleaf big_dripleaf pink_petals \
tube_coral brain_coral bubble_coral fire_coral horn_coral \
tube_coral_block brain_coral_block bubble_coral_block fire_coral_block horn_coral_block \
cherry_sapling hanging_roots twisting_vines twisting_vines_plant cobweb pointed_dripstone vine


# Nether portal
block.11500 = nether_portal
