/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	Pass: Blit voxy transparent data (since it is rendered before deferred pass)

--------------------------------------------------------------------------------
*/

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Input //===============================================================================//

layout(local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(RENDER_SCALE, RENDER_SCALE);

//======// Uniform //=============================================================================//

writeonly uniform uimage2D colorimg7;
writeonly uniform image2D colorimg8;

uniform usampler2D colortex16;
uniform sampler2D colortex17;

#include "/lib/universal/Uniform.glsl"

//======// Main //================================================================================//
void main() {
	ivec2 texelPos = ivec2(gl_GlobalInvocationID.xy);
	uvec4 materialData = texelFetch(colortex16, texelPos, 0);

	if (materialData.y > 0u && loadDepth1(texelPos) > 1.0 - EPS) {
		imageStore(colorimg7, texelPos, materialData);
		imageStore(colorimg8, texelPos, texelFetch(colortex17, texelPos, 0));
	}
}
