/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	References:
		Sébastien Hillaire. "A Scalable and Production Ready Sky and Atmosphere Rendering Technique". EGSR 2020.
            https://sebh.github.io/publications/egsr2020.pdf
		Epic Games, Inc. "Unreal Engine Sky Atmosphere Rendering Technique". 2020.
            https://github.com/sebh/UnrealEngineSkyAtmosphere

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 1, local_size_y = 1, local_size_z = 64) in;
const ivec3 workGroups = ivec3(32, 32, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image2D msLutImg;

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"

#include "/lib/universal/Random.glsl"

mat2x3 RaymarchMultiScattering(vec3 rayPos, vec3 rayDir, vec3 sunDir) {
    float tMax;
    bool groundHit;
    if (AtmosphereSetupRay(rayPos, rayDir, tMax, groundHit)) return mat2x3(0.0);

    float stepSize = tMax * rcp(float(ATMOSPHERE_MSLUT_SAMPLES));
    vec3 rayStep = stepSize * rayDir;
    rayPos += 0.5 * rayStep;

    vec3 lum = vec3(0.0), fms = vec3(0.0), transmittance = vec3(1.0);
    for (uint i = 0u; i < ATMOSPHERE_MSLUT_SAMPLES; ++i, rayPos += rayStep) {
        vec3 density = AtmosphereDensityAtPoint(rayPos);
        vec3 extinction = atmosphereExtinction * density;

        vec3 sampleTransmittance = exp(-stepSize * extinction);

        float tEarth = RaySphereIntersectNearest(rayPos, sunDir, atmosphere.bottomRadius);
        float earthShadow = step(tEarth, 0.0);

        vec3 inScattering = atmosphereScattering * density.xy;
        vec3 scatteringIntegral = (inScattering - inScattering * sampleTransmittance) / extinction;
        fms += scatteringIntegral * transmittance * earthShadow;

        vec3 sunTransmittance = AtmosphereTransmittanceToSun(rayPos, sunDir);
        scatteringIntegral *= uniformPhase * sunIrradiance * sunTransmittance;

        lum += scatteringIntegral * transmittance;
        transmittance *= sampleTransmittance;
    }

    // Ground diffuse
    if (groundHit) {
        float planetHeight = length(rayPos);
        vec3 upVector = rayPos / planetHeight;

        float sunZenithCos = dot(upVector, sunDir);
        vec3 transmittanceToSun = AtmosphereTransmittanceToSun(planetHeight, sunZenithCos);

        lum += sunIrradiance * atmosphere.groundAlbedo * rPI * saturate(sunZenithCos) * transmittance * transmittanceToSun;
    }

    return mat2x3(lum, fms);
}

shared vec3 sharedLum[64];
shared vec3 sharedFms[64];

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_WorkGroupID.xy);
	vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(msLutImg));

    float cosTheta = uv.x * 2.0 - 1.0;
    float height = mix(atmosphere.bottomRadius, atmosphere.topRadius, uv.y);

    vec3 rayPos = vec3(0.0, height, 0.0);
    vec3 sunDir = normalize(vec3(0.0, cosTheta, sqrt(1.0 - cosTheta * cosTheta)));

    const uint samples = 64u;
    const float rSamples = 1.0 / float(samples);

    uint i = gl_LocalInvocationID.z;

    vec3 rayDir = SampleUniformSphere(R2(i));
    mat2x3 res = RaymarchMultiScattering(rayPos, rayDir, sunDir) * rSamples;

    sharedLum[i] = res[0];
    sharedFms[i] = res[1];
	barrier();

	// 64 to 32
	if (i < 32) {
		sharedLum[i] += sharedLum[i + 32];
		sharedFms[i] += sharedFms[i + 32];
	}
	barrier();

	// 32 to 16
	if (i < 16) {
		sharedLum[i] += sharedLum[i + 16];
		sharedFms[i] += sharedFms[i + 16];
	}
	barrier();

	// 16 to 8 (16 is thread group min hardware size with intel, no sync required from there)
	if (i < 8) {
		sharedLum[i] += sharedLum[i + 8];
		sharedFms[i] += sharedFms[i + 8];
	}
	barrier();
	if (i < 4) {
		sharedLum[i] += sharedLum[i + 4];
		sharedFms[i] += sharedFms[i + 4];
	}
	barrier();
	if (i < 2) {
		sharedLum[i] += sharedLum[i + 2];
		sharedFms[i] += sharedFms[i + 2];
	}
	barrier();
	if (i < 1) {
		sharedLum[i] += sharedLum[i + 1];
		sharedFms[i] += sharedFms[i + 1];
	}
	barrier();
	if (i > 0) return;

	imageStore(msLutImg, tid, vec4(sharedLum[0] / (1.0 - sharedFms[0]), 1.0));
}