/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	References:
		Sébastien Hillaire. "A Scalable and Production Ready Sky and Atmosphere Rendering Technique". EGSR 2020.
			https://sebh.github.io/publications/egsr2020.pdf
		Epic Games, Inc. "Unreal Engine Sky Atmosphere Rendering Technique". 2020.
			https://github.com/sebh/UnrealEngineSkyAtmosphere

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(12, 12, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly restrict uniform image2D skyViewImg;

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"
#include "/lib/universal/Random.glsl"

vec3 RenderSkyView(vec2 uv) {
	float lightViewCos = 1.0 - sqr(uv.x) * 2.0;
	float height = atmosphereViewHeight;
	vec3 up = vec3(0.0, 1.0, 0.0);

	float vHorizon = sqrt(height * height - atmosphere.bottomRadius * atmosphere.bottomRadius);
	float beta = fastAcos(vHorizon / height);
	float zenithHorizon = PI - beta;

	float viewZenithCos;
	if (uv.y < 0.5) {
		float coord = 1.0 - 2.0 * uv.y;
		coord *= coord; // Non-linear mapping
		viewZenithCos = cos(zenithHorizon * (1.0 - coord));
	} else {
		float coord = uv.y * 2.0 - 1.0;
		coord *= coord; // Non-linear mapping
		viewZenithCos = cos(zenithHorizon + beta * coord);
	}
	float viewZenithSin = sqrt(1.0 - viewZenithCos * viewZenithCos);
	vec3 rayDir = vec3(viewZenithSin * lightViewCos, viewZenithCos, viewZenithSin * sqrt(1.0 - lightViewCos * lightViewCos));

	float sunZenithCos = dot(up, worldSunDir);
	vec3 sunDir = normalize(vec3(sqrt(1.0 - sunZenithCos * sunZenithCos), sunZenithCos, 0.0));

	vec3 lum = sunIrradiance * RaymarchScattering(atmosphereViewPos, rayDir, sunDir);
		lum += moonIrradiance * RaymarchScattering(atmosphereViewPos, rayDir, -sunDir);

	return lum;
}

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(skyViewImg));

	imageStore(skyViewImg, tid, EncodeRGBE8(RenderSkyView(uv)));
}
