/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	References:
		Sébastien Hillaire. "A Scalable and Production Ready Sky and Atmosphere Rendering Technique". EGSR 2020.
            https://sebh.github.io/publications/egsr2020.pdf
		Epic Games, Inc. "Unreal Engine Sky Atmosphere Rendering Technique". 2020.
            https://github.com/sebh/UnrealEngineSkyAtmosphere

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(12, 12, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly restrict uniform image2D skyViewImg;

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/atmosphere/Common.glsl"
#include "/lib/universal/Random.glsl"

vec3 RaymarchScattering(vec3 rayPos, vec3 rayDir, vec3 sunDir) {
    float cosTheta = dot(rayDir, sunDir);

    #ifndef PLANET_GROUND
        // Hacks to simulate atmosphere on the ground
        if (rayDir.y < 0.0) {
            rayDir.y *= saturate(exp2(atmosphereViewHeight * 1e-3 - atmosphere.topRadius * 1e-3));
            rayDir = normalize(rayDir);
        }
    #endif

    float tMax;
    bool groundHit;
    if (AtmosphereSetupRay(rayPos, rayDir, tMax, groundHit)) return vec3(0.0);

    vec2 phaseValue = AtmospherePhase(cosTheta);

    // Adaptive sample count
    const float maxSamples = ATMOSPHERE_SKY_SAMPLES;
	float sampleCount = round(maxSamples * saturate(0.5 + tMax * 1e-5));

    float stepSize = tMax * rcp(sampleCount);
    vec3 rayStep = stepSize * rayDir;
    rayPos += 0.5 * rayStep;

    vec3 lum = vec3(0.0);
    vec3 transmittance = vec3(1.0);
    for (uint i = 0u; i < uint(sampleCount); ++i, rayPos += rayStep) {
        vec3 density = AtmosphereDensityAtPoint(rayPos);
        vec3 extinction = atmosphereExtinction * density;

        float r = length(rayPos);
        float mu = dot(sunDir, rayPos) / r;

        vec3 sunTransmittance = AtmosphereTransmittanceToSun(r, mu);
        vec3 psiMs = AtmosphereMultiScattering(r, mu);

        vec3 inScattering = atmosphereScattering * (density.xy * phaseValue) * sunTransmittance;
        inScattering += atmosphereScattering * density.xy * psiMs;

        vec3 sampleTransmittance = exp(-stepSize * extinction);

        vec3 scatteringIntegral = (inScattering - inScattering * sampleTransmittance) / extinction;
        lum += scatteringIntegral * transmittance;

        transmittance *= sampleTransmittance;
    }

    // Ground diffuse
    if (groundHit) {
        float planetHeight = length(rayPos);
        vec3 upVector = rayPos / planetHeight;

        float sunZenithCos = dot(upVector, sunDir);
        vec3 transmittanceToSun = AtmosphereTransmittanceToSun(planetHeight, sunZenithCos);

        lum += atmosphere.groundAlbedo * rPI * saturate(sunZenithCos) * transmittance * transmittanceToSun;
    }

    return lum * sunIrradiance;
}

vec3 RenderSkyView(vec2 uv) {
    float lightViewCos = 1.0 - sqr(uv.x) * 2.0;
    float height = atmosphereViewHeight;
    vec3 up = vec3(0.0, 1.0, 0.0);

    float vHorizon = sqrt(height * height - atmosphere.bottomRadius * atmosphere.bottomRadius);
    float beta = fastAcos(vHorizon / height);
    float zenithHorizon = PI - beta;

    float viewZenithCos;
    if (uv.y < 0.5) {
        float coord = 1.0 - 2.0 * uv.y;
        coord *= coord; // Non-linear mapping
        viewZenithCos = cos(zenithHorizon * (1.0 - coord));
    } else {
        float coord = uv.y * 2.0 - 1.0;
        coord *= coord; // Non-linear mapping
        viewZenithCos = cos(zenithHorizon + beta * coord);
    }
    float viewZenithSin = sqrt(1.0 - viewZenithCos * viewZenithCos);
    vec3 rayDir = vec3(viewZenithSin * lightViewCos, viewZenithCos, viewZenithSin * sqrt(1.0 - lightViewCos * lightViewCos));

    float sunZenithCos = dot(up, worldSunDir);
    vec3 sunDir = normalize(vec3(sqrt(1.0 - sunZenithCos * sunZenithCos), sunZenithCos, 0.0));

    vec3 lum = RaymarchScattering(atmosphereViewPos, rayDir, sunDir);
        lum += RaymarchScattering(atmosphereViewPos, rayDir, -sunDir) * moonlightMult;

    lum = desaturate(lum, wetness * 0.5); // Post-process
    return lum * 128.0;
}

//======// Main //================================================================================//
void main() {
	ivec2 tid = ivec2(gl_GlobalInvocationID.xy);
	vec2 uv = (vec2(tid) + 0.5) * rcp(imageSize(skyViewImg));

	imageStore(skyViewImg, tid, vec4(RenderSkyView(uv), 1.0));
}