/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	Pass: Preparing data for super resolution

--------------------------------------------------------------------------------
*/

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Input //===============================================================================//

layout(local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(RENDER_SCALE, RENDER_SCALE);

//======// Uniform //=============================================================================//

restrict writeonly uniform image2D colorimg3; // Scaled scene color for SR
// restrict writeonly uniform image2D colorimg21; // Exposure value for SR

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Main //================================================================================//
void main() {
	ivec2 texelPos = ivec2(gl_GlobalInvocationID.xy);

    // if (texelPos.x + texelPos.y == 0) {
    //     imageStore(colorimg21, ivec2(0), vec4(exposure.value, 0.0, 0.0, 1.0));
    // }
    #if defined(MOTION_BLUR) || SR_ENABLE
		vec3 color = texelFetch(colortex0, texelPos, 0).rgb;
	#else
		vec3 color = texelFetch(colortex1, texelPos, 0).rgb;
	#endif
    imageStore(colorimg3, texelPos, vec4(color, 1.0));
}

/*
SR Enabled:
-0:
    TemporalAA:
        Motion Vector -> colortex8
A:
    Motion Blur Enabled: colortex1 -> colortex0
    Motion Blur Disabled: colortex1 -> colortex1
B:
    PrepareSR:
        colortex0 or colortex1 -> colortex3(scaled)
        # exposure.value(ssbo) -> colortex21(1x1 R16F)
C:
    Dispatch SR:
        colortex3(scaled size) -> color buffer
        depthtex0 -> depth buffer
        colortex8 -> motion vector buffer
        # colortex21 -> exposure buffer
    Epic Pro Max Giga Ultra`s Upscaling Technology:
        Upscaled Color -> colortex5
D:
    Grade:
        There are apply bloom,but i don`t know the effect of bloom on SR,hope it can be ignored
        1.Use colortex5 instead of colortex0 or colortex1
        2.Output to colortex5
E:
    Final:
        Use colortex5 as input buffer

SR Disabled:
-0:
    TemporalAA:
        Motion Vector -> colortex8 (just when motion blur enabled)
A:
    Motion Blur Enabled: colortex1 -> colortex0
    Motion Blur Disabled: colortex1 -> colortex1
B:
    Grade:
        1.Use colortex0 or colortex1 as input buffer
        2.Output to colortex0 (always)
C:
    Final:
        Use colortex5(when enabled render scale) or colortex0 as input buffer
*/
