/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	Pass: Preparing data for super resolution

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Images //============================================================================//


layout (rgba16f) restrict writeonly uniform image2D colorimg20; //Scaled scene color for SR
layout (r32f) restrict writeonly uniform image2D colorimg21; //Exposure value for SR

//======// Main //================================================================================//
void main() {
	ivec2 texelPos = ivec2(gl_GlobalInvocationID.xy);
    if (texelPos.x > int(scaledViewSize.x) || texelPos.y > int(scaledViewSize.y)) {
        return;
    }
    if (texelPos.x == 0 && texelPos.y == 0) {
        imageStore(colorimg21, ivec2(0), vec4(exposure.value, 0.0, 0.0, 1.0));
    }
    #ifdef MOTION_BLUR
		vec3 color = texelFetch(colortex0, texelPos, 0).rgb;
	#else
		vec3 color = texelFetch(colortex1, texelPos, 0).rgb;
	#endif
    imageStore(colorimg20, texelPos, vec4(color, 1.0));
}

/*
SR Enabled:
-0:
    TemporalAA:
        Motion Vector -> colortex3
A:
    Motion Blur Enabled: colortex1 -> colortex0
    Motion Blur Disabled: colortex1 -> colortex1
B:
    PrepareSR:
        colortex0 or colortex1 -> colortex20(scaled)
        exposure.value(ssbo) -> colortex21(1x1 R32F)
C:
    Dispatch SR:
        colortex20(scaled size) -> color buffer
        depthtex0 -> depth buffer
        colortex3 -> motion vector buffer
        colortex21 -> exposure buffer
    Epic Pro Max Giga Ultra`s Upscaling Technology:
        Upscaled Color -> colortex22
D:
    Grade:
        There are apply bloom,but i don`t know the effect of bloom on SR,hope it can be ignored
        1.Use colortex22 instead of colortex0 or colortex1
        2.Output to colortex5
E:
    Final:
        Use colortex5 as input buffer

SR Disabled:
-0:
    TemporalAA:
        Motion Vector -> colortex3 (just when motion blur enabled)
A:
    Motion Blur Enabled: colortex1 -> colortex0
    Motion Blur Disabled: colortex1 -> colortex1
B:
    Grade:
        1.Use colortex0 or colortex1 as input buffer
        2.Output to colortex0 (always)
C:
    Final:
        Use colortex5(when enabled render scale) or colortex0 as input buffer
*/
