/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2024 HaringPro
	Apache License 2.0

	Pass: Compute diffuse indirect lighting

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(0.5, 0.5);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly restrict uniform image2D colorimg3;

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Transform.glsl"
#include "/lib/universal/Fetch.glsl"
#include "/lib/universal/Random.glsl"

#include "/lib/atmosphere/Common.glsl"

#include "/lib/surface/BRDF.glsl"
#include "/lib/lighting/SSILVB.glsl"

float GetClosestDepth(in ivec2 texel) {
    float depth = loadDepth0(texel);

    for (uint i = 0u; i < 8u; ++i) {
        ivec2 sampleTexel = (offset3x3N[i] << 1) + texel;
        float sampleDepth = loadDepth0(sampleTexel);
        depth = min(depth, sampleDepth);
    }

    return depth;
}

//======// Main //================================================================================//
void main() {
    uvec2 localPos = QuadLayout16x16(gl_LocalInvocationIndex);
    ivec2 texelPos = ivec2(localPos + gl_WorkGroupID.xy * gl_WorkGroupSize.xy);

    ivec2 renderTexel = texelPos << 1;
	float depth = GetClosestDepth(renderTexel);
	// float depth = loadDepth0(renderTexel);
	#if defined LOD_MOD
		bool lodTerrainMask = depth > 1.0 - EPS;
		if (lodTerrainMask) depth = loadDepthTransLod(renderTexel);
	#endif

	if (depth < 1.0) {
		#if defined LOD_MOD
            if (lodTerrainMask) depth = ViewToScreenDepth(ScreenToViewDepthLod(depth));
		#endif
		vec3 worldNormal = FetchSurfaceNormal(renderTexel);

    	vec2 screenCoord = texelToUv(renderTexel);
		vec3 viewPos = ScreenToViewSpace(vec3(screenCoord, depth));

		float lightmapSky = Unpack2x8UY(loadMaterialPack(renderTexel).x);

		vec4 result = CalculateSSILVB(screenCoord, viewPos, worldNormal, lightmapSky);
		result.rgb = sRGBToYCoCg(result.rgb); // Convert to YCoCg color space (for filtering)
		imageStore(colorimg3, texelPos, result);
	}
}