/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

	Pass: Edge-Avoiding À-Trous Wavelet Filter
	Reference:  https://research.nvidia.com/sites/default/files/pubs/2017-07_Spatiotemporal-Variance-Guided-Filtering://svgf_preprint.pdf
				https://cescg.org/wp-content/uploads/2018/04/Dundr-Progressive-Spatiotemporal-Variance-Guided-Filtering-2.pdf

--------------------------------------------------------------------------------
*/

// #extension GL_NV_compute_shader_derivatives : enable

layout(local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(0.5, 0.5);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Image //===============================================================================//

layout(rgba16f) restrict uniform image2D colorimg3;

//======// Uniform //=============================================================================//

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"
#include "/lib/universal/Fetch.glsl"
#include "/lib/universal/Transform.glsl"

/*
const uint padRadius = 1;
const uvec2 sharedSize = gl_WorkGroupSize.xy + (padRadius << 1);

shared float sharedVariance[sharedSize.x][sharedSize.y];

void SharedPreload() {
	ivec2 groupBase = ivec2(gl_WorkGroupID.xy * gl_WorkGroupSize.xy - padRadius);

	const uint sharedArea = sharedSize.x * sharedSize.y;
	const uint groupArea = gl_WorkGroupSize.x * gl_WorkGroupSize.y;
	const uint stageNum = (sharedArea - 1) / groupArea + 1;

	uint localIndex = gl_LocalInvocationIndex;
	ivec2 localID = ivec2(localIndex % sharedSize.x, localIndex / sharedSize.x);

	ivec2 loadTexel = groupBase + localID;
	sharedVariance[localID.x][localID.y] = imageLoad(colorimg3, loadTexel).a;

	for (uint stage = 1u; stage < stageNum; ++stage) {
		localIndex = gl_LocalInvocationIndex + stage * groupArea;

		if (localIndex < sharedArea) {
			localID = ivec2(localIndex % sharedSize.x, localIndex / sharedSize.x);

			loadTexel = groupBase + localID;
			sharedVariance[localID.x][localID.y] = imageLoad(colorimg3, loadTexel).a;
		}
	}

	memoryBarrierShared();
	barrier();
}

float CalculateVariance(ivec2 texel) {
	// const float kernel[2] = float[2](1.0, 0.3);
	const float kernel[2][2] = {{0.25, 0.125}, {0.125, 0.0625}};

	float variance = 0.0;
	for (int x = -1; x <= 1; ++x) {
		for (int y = -1; y <= 1; ++y) {
			ivec2 varianceTexel = texel + ivec2(x, y);
			float weight = kernel[abs(x)][abs(y)];

			variance += sharedVariance[varianceTexel.x][varianceTexel.y] * weight;
		}
	}

	return variance;
}
*/

//======// Main //================================================================================//
void main() {
	// SharedPreload();

	uvec2 localPos = RemapThread16x16(gl_LocalInvocationIndex);
	ivec2 texelPos = ivec2(localPos + gl_WorkGroupID.xy * gl_WorkGroupSize.xy);

	vec3 normalDepthData = texelFetch(colortex14, texelPos, 0).rgb;
	// vec2 depthGradient = vec2(dFdx(normalDepthData.w), dFdy(normalDepthData.w));

	// 0.0625 0.125 0.0625
	// 0.125  0.25  0.125
	// 0.0625 0.125 0.0625
	// 3×3 kernel used multiple times in the algorithm

	const float kernel[8] = {0.0625, 0.125, 0.0625, 0.125, 0.125, 0.0625, 0.125, 0.0625};

	vec4 filteredColVar = imageLoad(colorimg3, texelPos);
	float centerLuma = filteredColVar.r; // We use YCoCg color space

	float frameIndex = texelFetch(colortex2, texelPos, 0).a;
	float historyFactor = saturate(frameIndex * 0.1 - 0.125);

	vec3 viewDir  = ScreenToViewDirRaw(texelToUvScaled(texelPos));
	vec3 geoNormal = mat3(gbufferModelView) * FetchGeometryNormal(texelPos);

	float NdotV = abs(dot(geoNormal, viewDir));
	vec2 offsetScale = oms(abs(geoNormal.xy) * oms(NdotV)) * ldexp(2.0, FILTER_PASS_INDEX);

	float invThresholdZ = 8.0 / normalDepthData.z;

	// float variance = CalculateVariance(ivec2(localPos + padRadius));
	float variance = filteredColVar.a;
	float sigmaL = -0.5 * inversesqrt(variance + EPS) * historyFactor;
	float sigmaN = 32.0 * exp2(-0.5 * variance / sqr(centerLuma)) * historyFactor;

	vec3 centerNormal = OctDecodeSnorm(normalDepthData.xy);

	float sumWeight = 1.0;
	// filteredColVar *= vec4(vec3(sumWeight), sumWeight * sumWeight);
	vec2 sampleTexelBase = vec2(texelPos) + (BlueNoise(texelPos, frameCounter + FILTER_PASS_INDEX) - 0.5) * offsetScale;

	for (uint i = 0u; i < 9u; ++i) {
		ivec2 sampleTexel = ivec2(round(sampleTexelBase + offset3x3[i] * offsetScale));
		if (clamp(sampleTexel, ivec2(1), ivec2(scaledHalfViewSize) - 2) == sampleTexel) {
			vec3 sampleAux = texelFetch(colortex14, sampleTexel, 0).rgb;

			vec4 sampleColVar = imageLoad(colorimg3, sampleTexel);
			float sampleLuma = sampleColVar.r; // We use YCoCg color space

			float weight = saturate(fma(abs(sampleAux.z - normalDepthData.z), invThresholdZ, 1.0));

			float logWeightN = log2(saturate(dot(OctDecodeSnorm(sampleAux.xy), centerNormal))) * sigmaN;
			float logWeightL = abs(sampleLuma - centerLuma) * sigmaL;
			weight *= saturate(exp2(logWeightN + logWeightL));

			filteredColVar += sampleColVar * vec4(vec3(weight), weight * weight);
			sumWeight += weight;
		}
	}

	sumWeight = 1.0 / sumWeight;
	filteredColVar *= vec4(vec3(sumWeight), sumWeight * sumWeight);
	imageStore(colorimg3, texelPos, min(filteredColVar, FP16_MAX));
}
