/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2026 HaringPro
	Apache License 2.0

    Pass: Edge-Avoiding À-Trous Wavelet Filter
	Reference:  https://research.nvidia.com/sites/default/files/pubs/2017-07_Spatiotemporal-Variance-Guided-Filtering://svgf_preprint.pdf
                https://cescg.org/wp-content/uploads/2018/04/Dundr-Progressive-Spatiotemporal-Variance-Guided-Filtering-2.pdf

--------------------------------------------------------------------------------
*/

// #extension GL_NV_compute_shader_derivatives : enable

layout (local_size_x = 8, local_size_y = 8) in;
const vec2 workGroupsRender = vec2(0.5, 0.5);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Image //===============================================================================//

layout (rgba16f) restrict uniform image2D colorimg3;

//======// Uniform //=============================================================================//

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

/*
const uint padRadius = 1;
const uvec2 sharedSize = gl_WorkGroupSize.xy + (padRadius << 1);

shared float sharedVariance[sharedSize.x][sharedSize.y];

void SharedPreload() {
    ivec2 groupBase = ivec2(gl_WorkGroupID.xy * gl_WorkGroupSize.xy - padRadius);

    const uint sharedArea = sharedSize.x * sharedSize.y;
    const uint groupArea = gl_WorkGroupSize.x * gl_WorkGroupSize.y;
    const uint stageNum = (sharedArea - 1) / groupArea + 1;

    uint localIndex = gl_LocalInvocationIndex;
    ivec2 localID = ivec2(localIndex % sharedSize.x, localIndex / sharedSize.x);

    ivec2 loadTexel = groupBase + localID;
    sharedVariance[localID.x][localID.y] = imageLoad(colorimg3, loadTexel).a;

    for (uint stage = 1u; stage < stageNum; ++stage) {
        localIndex = gl_LocalInvocationIndex + stage * groupArea;

        if (localIndex < sharedArea) {
            localID = ivec2(localIndex % sharedSize.x, localIndex / sharedSize.x);

            loadTexel = groupBase + localID;
        	sharedVariance[localID.x][localID.y] = imageLoad(colorimg3, loadTexel).a;
        }
    }

    memoryBarrierShared();
    barrier();
}

float CalculateVariance(in ivec2 texel) {
    // const float kernel[2] = float[2](1.0, 0.3);
	const float kernel[2][2] = {{0.25, 0.125}, {0.125, 0.0625}};

	float variance = 0.0;
	for (int x = -1; x <= 1; ++x) {
		for (int y = -1; y <= 1; ++y) {
			ivec2 varianceTexel = texel + ivec2(x, y);
			float weight = kernel[abs(x)][abs(y)];

			variance += sharedVariance[varianceTexel.x][varianceTexel.y] * weight;
		}
	}

	return variance;
}
*/

//======// Main //================================================================================//
void main() {
	// SharedPreload();

	uvec2 localPos = QuadLayout8x8(gl_LocalInvocationIndex);
	ivec2 texelPos = ivec2(localPos + gl_WorkGroupID.xy * gl_WorkGroupSize.xy);

	f16vec3 normalDepthData = f16vec3(texelFetch(colortex14, texelPos, 0).rgb);
	// vec2 depthGradient = vec2(dFdx(normalDepthData.w), dFdy(normalDepthData.w));

	// 0.0625 0.125 0.0625
	// 0.125  0.25  0.125
	// 0.0625 0.125 0.0625
	// 3×3 kernel used multiple times in the algorithm

	const float kernel[8] = {0.0625, 0.125, 0.0625, 0.125, 0.125, 0.0625, 0.125, 0.0625};

	f16vec4 filteredColVar = f16vec4(imageLoad(colorimg3, texelPos));
	float16_t centerLuma = filteredColVar.r; // We use YCoCg color space

	float frameIndex = texelFetch(colortex2, texelPos, 0).a;
	float16_t historyFactor = float16_t(saturate(frameIndex * rcp(12.0)) * 0.9 + 0.1);

	// float variance = CalculateVariance(ivec2(localPos + padRadius));
	float16_t variance = filteredColVar.a;
	float16_t variancePhi = float16_t(-0.5 * inversesqrt(variance + EPS));

	const float sigmaZ = -4.0 * inversesqrt(float(ATROUS_FILTER_SIZE));
	const float sigmaN = 32.0;

    f16vec3 worldNormal = f16vec3(OctDecodeSnorm(normalDepthData.xy));

	float16_t sumWeight = float16_t(1.0);
	// filteredColVar *= vec4(vec3(sumWeight), sumWeight * sumWeight);
	ivec2 randTexel = texelPos + ivec2((BlueNoise(texelPos, frameCounter + ATROUS_FILTER_SIZE) - 0.5) * float(min(ATROUS_FILTER_SIZE, 8)));

	ivec2 texelEnd = ivec2(halfViewEnd) - 1;

	for (uint i = 0u; i < 9u; ++i) {
		ivec2 sampleTexel = clamp(randTexel + offset3x3[i] * ATROUS_FILTER_SIZE, ivec2(1), texelEnd);
		f16vec3 sampleAux = f16vec3(texelFetch(colortex14, sampleTexel, 0).rgb);

		f16vec4 sampleColVar = f16vec4(imageLoad(colorimg3, sampleTexel));
		float16_t sampleLuma = sampleColVar.r; // We use YCoCg color space

		// wN = max(0, N0 · N1) ^ σN
		float logWeightN = log2(saturate(dot(OctDecodeSnorm(sampleAux.xy), worldNormal))) * sigmaN;
		// wD = exp(−|D0 − D1| / (|σD(grad · off)| + ε))
		float logWeightZ = abs(sampleAux.z - normalDepthData.z) * sigmaZ;
		// wL = exp(−|L0 − L1| / (σLvar + ε))
		float logWeightL = abs(sampleLuma - centerLuma) * variancePhi;

		float16_t weight = float16_t(exp2((logWeightN + logWeightZ + logWeightL) * historyFactor));

		filteredColVar += sampleColVar * f16vec4(f16vec3(weight), weight * weight);
		sumWeight += weight;
	}

	sumWeight = float16_t(1.0) / sumWeight;
	filteredColVar *= f16vec4(f16vec3(sumWeight), sumWeight * sumWeight);
	imageStore(colorimg3, texelPos, min(filteredColVar, FP16_MAX));
}